#include <string>
#include <stdexcept>
#include <iostream>
#include <vector>
#include <windows.h>

using std::string;
using std::cout;
using std::endl;
using std::cerr;
using std::wstring;
using std::to_string;
using std::runtime_error;

#include "../../wmiclasses.h"
#include "../../wmiutils.h"

/*
The MSFT_NetTCPConnection InstanceID follows a specific format generated by the WMI provider.
It uniquely identifies a TCP connection using its endpoints: LocalAddress??LocalPort??RemoteAddress??RemotePort.
The InstanceID is formatted as:LocalAddress??LocalPort??RemoteAddress??RemotePort
*/


namespace root::StandardCimv2 {

class MSFT_NetTCPConnection : public WmiClassTemplate<MSFT_NetTCPConnection> {
private:
public:
    WmiClass::EntityResult GetEntity(const string & wmiNamespace, const string & wmiClassname, const KeyPropertiesMap & keyProperties) const override {
        WmiClass::EntityResult result;
        std::string instanceId = get_InstanceID(keyProperties);
        return WmiClass::EntityResult{{"Name", instanceId}, {"Description", instanceId}};
    }

    WmiClass::AssociatorsResult GetAssociators(const string & wmiNamespace, const string & wmiClassname, const KeyPropertiesMap & keyProperties) const override {
        std::string instanceId = get_InstanceID(keyProperties);

        std::string computerName = Hostname();

        std::cout << "Adding associator for computer: " << computerName << std::endl;

        return WmiClass::AssociatorsResult{{"Win32_SystemDevices", computerName, "Win32_ComputerSystem.Name='" + computerName + "'"}};
    }

    WmiClass::ReferencesResult GetReferences(const string & wmiNamespace, const string & wmiClassname, const KeyPropertiesMap & keyProperties) const override {
        WmiClass::ReferencesResult result;
        std::string instanceId = get_InstanceID(keyProperties);

        auto filesVector = getFilesOf(instanceId);
        for (const auto & fileName : filesVector) {
            std::cout << "Adding reference for file: " << fileName << std::endl;

            DWORD dwAttrs = GetFileAttributesW(Utf8ToWide(fileName).c_str());
            if (dwAttrs != INVALID_FILE_ATTRIBUTES) {
                if (dwAttrs & FILE_ATTRIBUTE_DIRECTORY) {
                    result.push_back({"CIM_DirectoryContainsFile", fileName, "CIM_Directory.Name='" + fileName + "'"});
                } else {
                    result.push_back({"CIM_DirectoryContainsFile", fileName, "CIM_DataFile.Name='" + fileName + "'"});
                }
            }
        }

        return result;
    }
};

static MSFT_NetTCPConnection g_netTCPConnection;
} // namespace root::StandardCimv2
